name: Test

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt install libasound2-dev libdbus-1-dev pkg-config
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: bash tests/sympal/autotest.sh
