name: Sympal

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt install libasound2-dev libdbus-1-dev pkg-config
    - name: Install yt-dlp
      run: python3 -m pip install -U 'yt-dlp[default]'
    - name: Build
      run: cargo build --verbose
    - name: Fetch media
      run: bash tests/sympal/fetch_media.sh
    - name: Run tests
      run: bash tests/sympal/autotest.sh
